version: "3.6"

services:
  saliency:
    image: saliency-app:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      # IP:0.0 where IP is the IP address of host machine needed for VcXsrv
      - DISPLAY=10.0.0.34:0.0
    command:
      # paths to -vid, -par, and -dir are relative to directory mounted in `source:` below
      [
        "--vid=samples/vtest.avi",
        "--par=parameters.yml",
        "--dir=exports",
        "--start_frame=2",
        "--stop_frame=6",
      ]
    volumes:
      - type: bind
        # absolute path to the data to load on host machine
        source: $USERPROFILE/saliency/share
        target: /home/user/saliency/runtime
    container_name: bottom-up-visual-saliency
    privileged: true
# ----------------------------------------------------------
# Useful docker compose commands:
#  docker-compose up
#  docker-compose run --rm saliency
#  docker-compose run --rm --entrypoint /bin/bash saliency
